const quizLevels = [
    {
        level: 1,
        name: "Level 1 (Beginner)",
        vocab: [
            { word: "Ant", definition: "มด" },
            { word: "Apple", definition: "แอปเปิล" },
            { word: "Bag", definition: "กระเป๋า" },
            { word: "Ball", definition: "ลูกบอล" },
            { word: "Bat", definition: "ค้างคาว" },
            { word: "Bee", definition: "ผึ้ง" },
            { word: "Bin", definition: "ถังขยะ" },
            { word: "Bird", definition: "นก" },
            { word: "Book", definition: "หนังสือ" },
            { word: "Box", definition: "กล่อง" },
            { word: "Bus", definition: "รถประจำทาง" },
            { word: "Cake", definition: "ขนมเค้ก" },
            { word: "Cat", definition: "แมว" },
            { word: "Cow", definition: "วัว" },
            { word: "Cup", definition: "ถ้วย" },
            { word: "Desk", definition: "โต๊ะนักเรียน" },
            { word: "Dog", definition: "สุนัข" },
            { word: "Duck", definition: "เป็ด" },
            { word: "Ear", definition: "หู" },
            { word: "Egg", definition: "ไข่" },
            { word: "Eye", definition: "ตา" },
            { word: "Fan", definition: "พัดลม" },
            { word: "Fish", definition: "ปลา" },
            { word: "Hand", definition: "มือ" },
            { word: "Hat", definition: "หมวก" },
            { word: "Hen", definition: "แม่ไก่" },
            { word: "Jar", definition: "โอ่ง / ขวดโหล" },
            { word: "Kite", definition: "ว่าว" },
            { word: "Leg", definition: "ขา" },
            { word: "Map", definition: "แผนที่" }
        ]
    },
    {
        level: 2,
        name: "Level 2 (Basic Objects & People)",
        vocab: [
            { word: "Angry", definition: "โกรธ" },
            { word: "Arm", definition: "แขน" },
            { word: "Artist", definition: "ศิลปิน" },
            { word: "Ask", definition: "ถาม" },
            { word: "Aunt", definition: "ป้า, น้า, อา (หญิง)" },
            { word: "Baby", definition: "เด็กทารก" },
            { word: "Big", definition: "ใหญ่" },
            { word: "Blue", definition: "สีฟ้า/น้ำเงิน" },
            { word: "Body", definition: "ร่างกาย" },
            { word: "Brother", definition: "พี่ชาย, น้องชาย" },
            { word: "Chair", definition: "เก้าอี้" },
            { word: "Class", definition: "ชั้นเรียน" },
            { word: "Cold", definition: "หนาว, เย็น" },
            { word: "Cook", definition: "ทำอาหาร" },
            { word: "Dance", definition: "เต้นรำ" },
            { word: "Eat", definition: "กิน" },
            { word: "Face", definition: "ใบหน้า" },
            { word: "Farmer", definition: "ชาวนา" },
            { word: "Fat", definition: "อ้วน" },
            { word: "Father", definition: "พ่อ" },
            { word: "Glad", definition: "ดีใจ" },
            { word: "Home", definition: "บ้าน" },
            { word: "Idea", definition: "ความคิด" },
            { word: "Jam", definition: "แยม" },
            { word: "Job", definition: "งาน, อาชีพ" },
            { word: "Jug", definition: "เหยือกน้ำ" },
            { word: "King", definition: "พระราชา" },
            { word: "Lamp", definition: "โคมไฟ" },
            { word: "Love", definition: "รัก" },
            { word: "Mother", definition: "แม่" }
        ]
    },
    {
        level: 3,
        name: "Level 3 (Home & Activities)",
        vocab: [
            { word: "Bathroom", definition: "ห้องน้ำ" },
            { word: "Bedroom", definition: "ห้องนอน" },
            { word: "Buy", definition: "ซื้อ" },
            { word: "Clean", definition: "ทำความสะอาด" },
            { word: "Doctor", definition: "หมอ" },
            { word: "Draw", definition: "วาดภาพ" },
            { word: "Drink", definition: "ดื่ม" },
            { word: "Flower", definition: "ดอกไม้" },
            { word: "Friend", definition: "เพื่อน" },
            { word: "Fruit", definition: "ผลไม้" },
            { word: "Garden", definition: "สวน" },
            { word: "Give", definition: "ให้" },
            { word: "Go", definition: "ไป" },
            { word: "Happy", definition: "มีความสุข" },
            { word: "Hippo", definition: "ฮิปโปโปเตมัส" },
            { word: "Hit", definition: "ตี" },
            { word: "Hop", definition: "กระโดด (ขาเดียว)" },
            { word: "Horse", definition: "ม้า" },
            { word: "House", definition: "บ้าน (สิ่งปลูกสร้าง)" },
            { word: "Hungry", definition: "หิว" },
            { word: "Kitchen", definition: "ห้องครัว" },
            { word: "Market", definition: "ตลาด" },
            { word: "Noon", definition: "เที่ยงวัน" },
            { word: "Nurse", definition: "พยาบาล" },
            { word: "Ox", definition: "วัวตัวผู้" },
            { word: "Pair", definition: "คู่" },
            { word: "Painting", definition: "ภาพวาด" },
            { word: "Play", definition: "เล่น" },
            { word: "Queen", definition: "พระราชินี" },
            { word: "Rabbit", definition: "กระต่าย" }
        ]
    },
    {
        level: 4,
        name: "Level 4 (School & Time)",
        vocab: [
            { word: "Afternoon", definition: "ตอนบ่าย" },
            { word: "Always", definition: "เสมอ" },
            { word: "Around", definition: "รอบๆ" },
            { word: "At", definition: "ที่" },
            { word: "Balloon", definition: "ลูกโป่ง" },
            { word: "Behind", definition: "ข้างหลัง" },
            { word: "Between", definition: "ระหว่าง" },
            { word: "Borrow", definition: "ขอยืม" },
            { word: "Breakfast", definition: "อาหารเช้า" },
            { word: "Brush", definition: "แปรง" },
            { word: "Cafeteria", definition: "โรงอาหาร" },
            { word: "Clock", definition: "นาฬิกา (แขวน)" },
            { word: "Comb", definition: "หวี" },
            { word: "Dinner", definition: "อาหารเย็น" },
            { word: "Doll", definition: "ตุ๊กตา" },
            { word: "English", definition: "ภาษาอังกฤษ" },
            { word: "Evening", definition: "ตอนเย็น" },
            { word: "Homework", definition: "การบ้าน" },
            { word: "Library", definition: "ห้องสมุด" },
            { word: "Lunch", definition: "อาหารกลางวัน" },
            { word: "Math", definition: "คณิตศาสตร์" },
            { word: "Morning", definition: "ตอนเช้า" },
            { word: "Music", definition: "ดนตรี" },
            { word: "Next to", definition: "ถัดจาก" },
            { word: "Playground", definition: "สนามเด็กเล่น" },
            { word: "Science", definition: "วิทยาศาสตร์" },
            { word: "Subject", definition: "วิชา" },
            { word: "Tomorrow", definition: "พรุ่งนี้" },
            { word: "Under", definition: "ใต้" },
            { word: "Weekend", definition: "สุดสัปดาห์" }
        ]
    },
    {
        level: 5,
        name: "Level 5 (Health & Community)",
        vocab: [
            { word: "Address", definition: "ที่อยู่" },
            { word: "Camera", definition: "กล้องถ่ายรูป" },
            { word: "Collect", definition: "สะสม" },
            { word: "Computer", definition: "คอมพิวเตอร์" },
            { word: "Cough", definition: "ไอ" },
            { word: "Dentist", definition: "ทันตแพทย์" },
            { word: "Dress up", definition: "แต่งตัวแฟนซี" },
            { word: "Driver", definition: "คนขับรถ" },
            { word: "Eggplant", definition: "มะเขือยาว" },
            { word: "Envelope", definition: "ซองจดหมาย" },
            { word: "Factory", definition: "โรงงาน" },
            { word: "Famous", definition: "มีชื่อเสียง" },
            { word: "Fever", definition: "ไข้" },
            { word: "Forest", definition: "ป่าไม้" },
            { word: "Gardening", definition: "การทำสวน" },
            { word: "Headache", definition: "ปวดหัว" },
            { word: "Hobby", definition: "งานอดิเรก" },
            { word: "Hospital", definition: "โรงพยาบาล" },
            { word: "Letter", definition: "จดหมาย" },
            { word: "Medicine", definition: "ยา" },
            { word: "Plant", definition: "พืช / ปลูก" },
            { word: "Police", definition: "ตำรวจ" },
            { word: "Post office", definition: "ที่ทำการไปรษณีย์" },
            { word: "Reporter", definition: "ผู้สื่อข่าว" },
            { word: "Stamp", definition: "ดวงตราไปรษณียากร" },
            { word: "Stomachache", definition: "ปวดท้อง" },
            { word: "Telephone", definition: "โทรศัพท์" },
            { word: "Temperature", definition: "อุณหภูมิ" },
            { word: "Toothache", definition: "ปวดฟัน" },
            { word: "Vegetable", definition: "ผัก" }
        ]
    },
    {
        level: 6,
        name: "Level 6 (Travel & Culture)",
        vocab: [
            { word: "Airport", definition: "สนามบิน" },
            { word: "Ancient", definition: "โบราณ" },
            { word: "Bridge", definition: "สะพาน" },
            { word: "Buddhism", definition: "ศาสนาพุทธ" },
            { word: "Ceremony", definition: "พิธีการ" },
            { word: "Church", definition: "โบสถ์คริสต์" },
            { word: "Culture", definition: "วัฒนธรรม" },
            { word: "Delicious", definition: "อร่อย" },
            { word: "Direction", definition: "ทิศทาง" },
            { word: "Excited", definition: "รู้สึกตื่นเต้น" },
            { word: "Festival", definition: "เทศกาล" },
            { word: "Foreigner", definition: "ชาวต่างชาติ" },
            { word: "Guide", definition: "มัคคุเทศก์" },
            { word: "Holiday", definition: "วันหยุด" },
            { word: "Journey", definition: "การเดินทาง" },
            { word: "Location", definition: "สถานที่ตั้ง" },
            { word: "Monk", definition: "พระสงฆ์" },
            { word: "Museum", definition: "พิพิธภัณฑ์" },
            { word: "North", definition: "ทิศเหนือ" },
            { word: "Pagoda", definition: "เจดีย์" },
            { word: "Palace", definition: "พระราชวัง" },
            { word: "Passenger", definition: "ผู้โดยสาร" },
            { word: "Picnic", definition: "การตั้งวงกินอาหารนอกบ้าน" },
            { word: "Province", definition: "จังหวัด" },
            { word: "Religion", definition: "ศาสนา" },
            { word: "Restaurant", definition: "ร้านอาหาร" },
            { word: "Sanctuary", definition: "เขตห้ามล่าสัตว์/สถานที่ศักดิ์สิทธิ์" },
            { word: "South", definition: "ทิศใต้" },
            { word: "Temple", definition: "วัด" },
            { word: "Tourist", definition: "นักท่องเที่ยว" }
        ]
    },
    {
        level: 7,
        name: "Level 7 (Adjectives & Descriptions)",
        vocab: [
            { word: "Activity", definition: "กิจกรรม" },
            { word: "Adventure", definition: "การผจญภัย" },
            { word: "Boring", definition: "น่าเบื่อ" },
            { word: "Careful", definition: "ระมัดระวัง" },
            { word: "Century", definition: "ศตวรรษ" },
            { word: "Cheap", definition: "ราคาถูก" },
            { word: "Dangerous", definition: "อันตราย" },
            { word: "Different", definition: "แตกต่าง" },
            { word: "Difficult", definition: "ยาก" },
            { word: "Exciting", definition: "น่าตื่นเต้น" },
            { word: "Expensive", definition: "ราคาแพง" },
            { word: "Favorite", definition: "ที่โปรดปราน" },
            { word: "Friendly", definition: "เป็นมิตร" },
            { word: "Funny", definition: "ตลก" },
            { word: "Habit", definition: "นิสัย" },
            { word: "Heavy", definition: "หนัก" },
            { word: "High", definition: "สูง" },
            { word: "Important", definition: "สำคัญ" },
            { word: "Interesting", definition: "น่าสนใจ" },
            { word: "Language", definition: "ภาษา" },
            { word: "Lazy", definition: "ขี้เกียจ" },
            { word: "Low", definition: "ต่ำ" },
            { word: "Magazine", definition: "นิตยสาร" },
            { word: "Modern", definition: "ทันสมัย" },
            { word: "Popular", definition: "เป็นที่นิยม" },
            { word: "Practice", definition: "ฝึกฝน" },
            { word: "Same", definition: "เหมือนกัน" },
            { word: "Science", definition: "วิทยาศาสตร์" },
            { word: "Short", definition: "สั้น / เตี้ย" },
            { word: "Tall", definition: "สูง" }
        ]
    },
    {
        level: 8,
        name: "Level 8 (Concepts & Environment)",
        vocab: [
            { word: "Amazing", definition: "น่าทึ่ง" },
            { word: "Apologize", definition: "ขอโทษ (ทางการ)" },
            { word: "Believe", definition: "เชื่อ" },
            { word: "Capital", definition: "เมืองหลวง" },
            { word: "Celebration", definition: "การเฉลิมฉลอง" },
            { word: "Crowded", definition: "แออัด" },
            { word: "Decide", definition: "ตัดสินใจ" },
            { word: "Describe", definition: "บรรยาย" },
            { word: "Destination", definition: "จุดหมายปลายทาง" },
            { word: "Entertainment", definition: "ความบันเทิง" },
            { word: "Environment", definition: "สิ่งแวดล้อม" },
            { word: "Equipment", definition: "อุปกรณ์" },
            { word: "Experience", definition: "ประสบการณ์" },
            { word: "Garbage", definition: "ขยะ" },
            { word: "Guess", definition: "เดา" },
            { word: "Information", definition: "ข้อมูล" },
            { word: "Instrument", definition: "เครื่องมือ/ดนตรี" },
            { word: "Invitation", definition: "การเชิญ" },
            { word: "Knowledge", definition: "ความรู้" },
            { word: "Luggage", definition: "กระเป๋าเดินทาง" },
            { word: "Mystery", definition: "เรื่องลึกลับ" },
            { word: "Natural", definition: "ธรรมชาติ" },
            { word: "Opinion", definition: "ความคิดเห็น" },
            { word: "Pollution", definition: "มลพิษ" },
            { word: "Protect", definition: "ปกป้อง" },
            { word: "Recycle", definition: "รีไซเคิล" },
            { word: "Traffic", definition: "การจราจร" },
            { word: "Transport", definition: "การขนส่ง" },
            { word: "Vacation", definition: "ช่วงเวลาพักผ่อน" },
            { word: "Weather", definition: "สภาพอากาศ" }
        ]
    },
    {
        level: 9,
        name: "Level 9 (Intermediate Actions & Society)",
        vocab: [
            { word: "Abandon", definition: "ละทิ้ง" },
            { word: "Ability", definition: "ความสามารถ" },
            { word: "Absolutely", definition: "อย่างแน่นอน" },
            { word: "Achievement", definition: "ความสำเร็จ" },
            { word: "Adjust", definition: "ปรับตัว" },
            { word: "Admire", definition: "ชื่นชม" },
            { word: "Advantage", definition: "ข้อดี" },
            { word: "Ambition", definition: "ความทะเยอทะยาน" },
            { word: "Architect", definition: "สถาปนิก" },
            { word: "Career", definition: "อาชีพ/ความก้าวหน้า" },
            { word: "Challenge", definition: "ความท้าทาย" },
            { word: "Charity", definition: "การกุศล" },
            { word: "Communication", definition: "การสื่อสาร" },
            { word: "Confident", definition: "มั่นใจ" },
            { word: "Destroy", definition: "ทำลาย" },
            { word: "Effect", definition: "ผลกระทบ" },
            { word: "Employ", definition: "จ้างงาน" },
            { word: "Encourage", definition: "ให้กำลังใจ" },
            { word: "Harmful", definition: "เป็นอันตราย" },
            { word: "Health", definition: "สุขภาพ" },
            { word: "Improve", definition: "ปรับปรุง" },
            { word: "Inspire", definition: "สร้างแรงบันดาลใจ" },
            { word: "Keep", definition: "เก็บ/รักษา" },
            { word: "Kind", definition: "ชนิด / ใจดี" },
            { word: "Know", definition: "รู้" },
            { word: "Manage", definition: "จัดการ" },
            { word: "Necessary", definition: "จำเป็น" },
            { word: "Opportunity", definition: "โอกาส" },
            { word: "Passenger", definition: "ผู้โดยสาร" },
            { word: "Technology", definition: "เทคโนโลยี" }
        ]
    },
    {
        level: 10,
        name: "Level 10 (Academic & Abstract)",
        vocab: [
            { word: "Analyze", definition: "วิเคราะห์" },
            { word: "Ancient", definition: "โบราณ" },
            { word: "Appearance", definition: "รูปลักษณ์" },
            { word: "Benefit", definition: "ประโยชน์" },
            { word: "Biology", definition: "ชีววิทยา" },
            { word: "Character", definition: "ตัวละคร/นิสัย" },
            { word: "Competitor", definition: "คู่แข่ง" },
            { word: "Concentrate", definition: "มีสมาธิ" },
            { word: "Consume", definition: "บริโภค" },
            { word: "Culture", definition: "วัฒนธรรม" },
            { word: "Data", definition: "ข้อมูล" },
            { word: "Decrease", definition: "ลดลง" },
            { word: "Disaster", definition: "ภัยพิบัติ" },
            { word: "Education", definition: "การศึกษา" },
            { word: "Essential", definition: "จำเป็นที่สุด" },
            { word: "Fluent", definition: "คล่องแคล่ว" },
            { word: "Generation", definition: "รุ่นคน" },
            { word: "Global", definition: "ทั่วโลก" },
            { word: "Identify", definition: "ระบุ" },
            { word: "Impact", definition: "ผลกระทบ" },
            { word: "Increase", definition: "เพิ่มขึ้น" },
            { word: "Influence", definition: "มีอิทธิพล" },
            { word: "Method", definition: "วิธีการ" },
            { word: "Organize", definition: "จัดระเบียบ" },
            { word: "Predict", definition: "ทำนาย" },
            { word: "Quality", definition: "คุณภาพ" },
            { word: "Solution", definition: "ทางแก้" },
            { word: "Species", definition: "สายพันธุ์" },
            { word: "Stereotype", definition: "การเหมารวม" },
            { word: "Traditional", definition: "แบบดั้งเดิม" }
        ]
    },
    {
        level: 11,
        name: "Level 11 (Advanced I)",
        vocab: [
            { word: "Accomplish", definition: "บรรลุผลสำเร็จ" },
            { word: "Alternative", definition: "ทางเลือก" },
            { word: "Appropriate", definition: "เหมาะสม" },
            { word: "Argument", definition: "ข้อโต้แย้ง" },
            { word: "Attitude", definition: "ทัศนคติ" },
            { word: "Candidate", definition: "ผู้สมัคร" },
            { word: "Complex", definition: "ซับซ้อน" },
            { word: "Consequence", definition: "ผลที่ตามมา" },
            { word: "Consumer", definition: "ผู้บริโภค" },
            { word: "Contribute", definition: "มีส่วนร่วม" },
            { word: "Criticize", definition: "วิพากษ์วิจารณ์" },
            { word: "Crucial", definition: "สำคัญมาก" },
            { word: "Demonstrate", definition: "สาธิต" },
            { word: "Diversity", definition: "ความหลากหลาย" },
            { word: "Economic", definition: "เกี่ยวกับเศรษฐกิจ" },
            { word: "Eliminate", definition: "กำจัด" },
            { word: "Emphasis", definition: "การเน้นย้ำ" },
            { word: "Evidence", definition: "หลักฐาน" },
            { word: "Factor", definition: "ปัจจัย" },
            { word: "Feature", definition: "คุณลักษณะ" },
            { word: "Generate", definition: "สร้าง/ผลิต" },
            { word: "Hypothesis", definition: "สมมติฐาน" },
            { word: "Investigate", definition: "สืบสวน" },
            { word: "Issue", definition: "ประเด็น/ปัญหา" },
            { word: "Obvious", definition: "ชัดเจน" },
            { word: "Potential", definition: "ศักยภาพ" },
            { word: "Preserve", definition: "อนุรักษ์" },
            { word: "Reliable", definition: "เชื่อถือได้" },
            { word: "Significant", definition: "มีนัยสำคัญ" },
            { word: "Structure", definition: "โครงสร้าง" }
        ]
    },
    {
        level: 12,
        name: "Level 12 (Advanced II)",
        vocab: [
            { word: "Abundant", definition: "อุดมสมบูรณ์" },
            { word: "Accurate", definition: "ถูกต้องแม่นยำ" },
            { word: "Acknowledge", definition: "รับทราบ/ยอมรับ" },
            { word: "Acquire", definition: "ได้รับ/เรียนรู้" },
            { "word": "Advocate", "definition": "สนับสนุน" },
            { "word": "Ambiguous", "definition": "กำกวม" },
            { "word": "Beneficial", "definition": "เป็นประโยชน์" },
            { "word": "Bias", "definition": "อคติ" },
            { "word": "Collaborate", "definition": "ร่วมมือ" },
            { "word": "Comprehensive", "definition": "ครอบคลุม" },
            { "word": "Considerable", "definition": "มากมาย" },
            { "word": "Contradict", "definition": "ขัดแย้ง" },
            { "word": "Decline", "definition": "ปฏิเสธ / ลดลง" },
            { "word": "Determine", "definition": "กำหนด/ตัดสินใจ" },
            { "word": "Distinguish", "definition": "แยกแยะ" },
            { "word": "Efficient", "definition": "มีประสิทธิภาพ" },
            { "word": "Fluctuate", "definition": "ผันผวน" },
            { "word": "Implication", "definition": "นัยยะ" },
            { "word": "Inevitable", "definition": "หลีกเลี่ยงไม่ได้" },
            { "word": "Interpretation", "definition": "การตีความ" },
            { "word": "Neglect", "definition": "ละเลย" },
            { "word": "Negotiate", "definition": "เจรจาต่อรอง" },
            { "word": "Objective", "definition": "วัตถุประสงค์ / เป็นกลาง" },
            { "word": "Perspective", "definition": "มุมมอง" },
            { "word": "Reluctant", "definition": "ลังเล/ไม่เต็มใจ" },
            { "word": "Sophisticated", "definition": "ซับซ้อน/ทันสมัย" },
            { "word": "Substantial", "definition": "มากมาย" },
            { "word": "Sustainable", "definition": "ยั่งยืน" },
            { "word": "Valid", "definition": "สมเหตุสมผล" },
            { "word": "Vulnerable", "definition": "เปราะบาง" }
        ]
    }
];
